import { Hero } from './hero';

export const HEROES: Hero[] = [
  { id: 11, name: 'KOMA (Eppley Airfield)', callsign: 'AAL1046', cid: '811885', realname: 'George Morris KPWK', clienttype: 'PILOT', frequency: '', latitude: '41.97298', longitude: '-87.90092', altitude: '676', groundspeed: '0', planned_aircraft: 'B738/L', planned_tascruise: '427', planned_depairport: 'KMSP', planned_altitude: '35000', planned_destairport: 'KORD', server: 'USA-EAST', protrevision: '100', rating: '1', transponder: '1363', facilitytype: '', visualrange: '', planned_revision: '2', planned_flighttype: 'I', planned_deptime: '1557', planned_actdeptime: '0', planned_hrsenroute: '1', planned_minenroute: '1', planned_hrsfuel: '2', planned_minfuel: '50', planned_altairport: 'KDTW', planned_remarks: 'PBN/A1B1C1D1S1S2 NAV/RNVD1E2A1 DAT/V DOF/191109 REG/N806SB EET/KZAU0020 RMK/NRP SIMBRIEF /v/', planned_route: 'RST1 RST ZZIPR FYTTE5', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110185913', heading: '90', QNH_iHg: '30.039', QNH_Mb: '1017', },
      { id: 12, name: 'KDSM (Des Moines International Airport)', callsign: 'AAL122', cid: '1229826', realname: '1229826', clienttype: 'PILOT', frequency: '', latitude: '41.97363', longitude: '-87.89842', altitude: '676', groundspeed: '2', planned_aircraft: 'B738/L', planned_tascruise: '451', planned_depairport: 'KORD', planned_altitude: '26000', planned_destairport: 'KMSP', server: 'USA-EAST', protrevision: '100', rating: '1', transponder: '2000', facilitytype: '', visualrange: '', planned_revision: '2', planned_flighttype: 'I', planned_deptime: '2215', planned_actdeptime: '2215', planned_hrsenroute: '1', planned_minenroute: '8', planned_hrsfuel: '2', planned_minfuel: '46', planned_altairport: 'KDSM', planned_remarks: '+VFPS+/V/PBN/A1B1C1D1S1S2 DOF/191110 REG/N901NN EET/KZMP0034 OPR/AAL PER/C RMK/TCAS SIMBRIEF', planned_route: 'PMPKN NEATO DLLAN RONIC KAMMA KKILR3', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110215456', heading: '333', QNH_iHg: '30.039', QNH_Mb: '1017',     },
      { id: 13, name: 'KGRB (Green Bay Austin Straubel International Airport)', callsign: 'AAL787', cid: '810603', realname: 'Fred Clausen KABQ', clienttype: 'PILOT', frequency: '', latitude: '29.41459', longitude: '-91.56274', altitude: '37173', groundspeed: '561', planned_aircraft: 'H/B77W/L', planned_tascruise: '0', planned_depairport: 'KLAX', planned_altitude: '37000', planned_destairport: 'KMIA', server: 'USA-EAST', protrevision: '100', rating: '1', transponder: '4634', facilitytype: '', visualrange: '', planned_revision: '5', planned_flighttype: 'I', planned_deptime: '0', planned_actdeptime: '0', planned_hrsenroute: '0', planned_minenroute: '0', planned_hrsfuel: '0', planned_minfuel: '0', planned_altairport: '', planned_remarks: 'www.joinava.org / twitch.tv/ba747heavy  /v/ SEL/FRED', planned_route: '+DOTSS2 CNERY BLH J65 KOFFA J169 TFD J50 ELP J2 JCT J86 LEV Y290 BLVNS Y290 BAGGS SSCOT5', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110184126', heading: '97', QNH_iHg: '30.092', QNH_Mb: '1019',     },
      { id: 14, name: 'KLNK (Lincoln Airport)',callsign: 'BAW16WF', cid: '810658', realname: 'Ian Abel KMSP', clienttype: 'PILOT', frequency: '', latitude: '-31.78878', longitude: '150.75367', altitude: '39137', groundspeed: '476', planned_aircraft: 'H/B744/L', planned_tascruise: '487', planned_depairport: 'YBCS', planned_altitude: '39000', planned_destairport: 'YSSY', server: 'USA-EAST', protrevision: '100', rating: '1', transponder: '2000', facilitytype: '', visualrange: '', planned_revision: '2', planned_flighttype: 'I', planned_deptime: '635', planned_actdeptime: '0', planned_hrsenroute: '2', planned_minenroute: '30', planned_hrsfuel: '4', planned_minfuel: '53', planned_altairport: 'YMML', planned_remarks: 'PBN/A1B1D1L1O1S2 NAV/RNVD1E2A1 SUR/TCAS DOF/191110 REG/GCIVA EET/YMMM0224 SEL/AKQR OPR/BAW RVR/075 RMK/TCAS LAHSO NOT AUTHORISED SIMBRIEF /v/', planned_route: 'SWIFT Y153 ROKUU H12 BOREE BOREE1A', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110205543', heading: '170', QNH_iHg: '30.056', QNH_Mb: '1017',     },
      { id: 15, name: 'KOFF (Offutt Air Force Base)', callsign: 'DAL1340', cid: '1218385', realname: 'Benjamin S KSDF', clienttype: 'PILOT', frequency: '', latitude: '44.88429', longitude: '-93.20670', altitude: '847', groundspeed: '2', planned_aircraft: 'A319/L', planned_tascruise: '431', planned_depairport: 'KMSP', planned_altitude: '37000', planned_destairport: 'KSDF', server: 'USA-EAST', protrevision: '100', rating: '1', transponder: '2000', facilitytype: '', visualrange: '', planned_revision: '1', planned_flighttype: 'I', planned_deptime: '1810', planned_actdeptime: '1810', planned_hrsenroute: '1', planned_minenroute: '11', planned_hrsfuel: '2', planned_minfuel: '46', planned_altairport: 'KCVG', planned_remarks: '+VFPS+/V/PBN/A1B1C1D1O1S1 DOF/191110 REG/N319SB EET/KZAU0016 KZID0047 OPR/DAL PER/C RMK/TCAS SIMBRIEF', planned_route: 'ZMBRO7 ODI J30 JOT RAMSE FRIZN5', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110220124', heading: '210', QNH_iHg: '30.002', QNH_Mb: '1015', 
    },
      { id: 16, name: 'KOMA (Eppley Airfield)', callsign: 'DAL1734', cid: '1325328', realname: 'Alex BERGER LTBA', clienttype: 'PILOT', frequency: '', latitude: '42.66172', longitude: '-85.14114', altitude: '35075', groundspeed: '561', planned_aircraft: 'B738/L', planned_tascruise: '442', planned_depairport: 'KMSP', planned_altitude: '35000', planned_destairport: 'KLGA', server: 'UK-1', protrevision: '100', rating: '1', transponder: '1000', facilitytype: '', visualrange: '', planned_revision: '1', planned_flighttype: 'I', planned_deptime: '2110', planned_actdeptime: '2110', planned_hrsenroute: '1', planned_minenroute: '53', planned_hrsfuel: '3', planned_minfuel: '5', planned_altairport: 'KHPN', planned_remarks: '+VFPS+/V/PBN/B1D1O1S1 DOF/191110 REG/N3734D EET/KZAU0019 KZOB0046 KZNY0122 PER/C ', planned_route: 'COULT7 DLL J34 WOOST J146 ETG MIP4 ', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110213755', heading: '117', QNH_iHg: '29.993', QNH_Mb: '1015', 
    },
      { id: 17, name: 'KMSP (Minneapolis−Saint Paul International Airport)', callsign: 'DAL1779', cid: '1183945', realname: 'Chris Ferguson KDFW', clienttype: 'PILOT', frequency: '', latitude: '44.36987', longitude: '-95.41175', altitude: '31546', groundspeed: '500', planned_aircraft: 'B739/L', planned_tascruise: '455', planned_depairport: 'KDEN', planned_altitude: '35000', planned_destairport: 'KMSP', server: 'USA-WEST', protrevision: '100', rating: '1', transponder: '614', facilitytype: '', visualrange: '', planned_revision: '1', planned_flighttype: 'I', planned_deptime: '2030', planned_actdeptime: '0', planned_hrsenroute: '1', planned_minenroute: '30', planned_hrsfuel: '3', planned_minfuel: '42', planned_altairport: 'KDSM', planned_remarks: 'PBN/A1B1C1D1S1S2 NAV/RNVD1E2A1 DAT/V DOF/191110 REG/N845DN EET/KZMP0041 RMK/NRP SIMBRIEF /t/ SEL/BHFK', planned_route: 'YOKES6 CHICI HAAND KD75A SSWAN TORGY3', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110200504', heading: '51', QNH_iHg: '30.262', QNH_Mb: '1024', 
    },
      { id: 18, name: 'KDSM (Des Moines International Airport)', callsign: 'DAL2066', cid: '1131918', realname: 'Zach Avery KMSP', clienttype: 'PILOT', frequency: '', latitude: '40.62511', longitude: '-112.07717', altitude: '8932', groundspeed: '286', planned_aircraft: 'A320/L', planned_tascruise: '429', planned_depairport: 'KBZN', planned_altitude: '33000', planned_destairport: 'KSLC', server: 'USA-WEST', protrevision: '100', rating: '1', transponder: '2200', facilitytype: '', visualrange: '', planned_revision: '2', planned_flighttype: 'I', planned_deptime: '2015', planned_actdeptime: '2015', planned_hrsenroute: '0', planned_minenroute: '53', planned_hrsfuel: '2', planned_minfuel: '20', planned_altairport: 'KEVW', planned_remarks: '+VFPS+/V/PBN/A1B1C1D1O1S1 DOF/191110 REG/N320SB OPR/DAL PER/C RMK/TCAS SIMBRIEF', planned_route: 'TEERX4 DBS NORDK6', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110200047', heading: '175', QNH_iHg: '30.126', QNH_Mb: '1020', 
    },
      { id: 19, name: 'KGRB (Green Bay Austin Straubel International Airport)', callsign: 'DAL2328', cid: '1071809', realname: 'Liam Duffy KRDU', clienttype: 'PILOT', frequency: '', latitude: '47.05340', longitude: '-116.72320', altitude: '35305', groundspeed: '552', planned_aircraft: 'B739/L', planned_tascruise: '499', planned_depairport: 'KSEA', planned_altitude: '35000', planned_destairport: 'KMSP', server: 'SYD-1', protrevision: '100', rating: '1', transponder: '1520', facilitytype: '', visualrange: '', planned_revision: '2', planned_flighttype: 'I', planned_deptime: '115', planned_actdeptime: '0', planned_hrsenroute: '7', planned_minenroute: '7', planned_hrsfuel: '9', planned_minfuel: '21', planned_altairport: 'KDLH', planned_remarks: 'deltava.org /v/ SEL/LDLD', planned_route: 'SEA NORMY J90 HLN DPR UFFDA TORGY3', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110204442', heading: '90', QNH_iHg: '30.216', QNH_Mb: '1023', 
    },
      { id: 20, name: 'KLNK (Lincoln Airport)', callsign: 'DAL2475', cid: '1240191', realname: 'Daniel Everman KSJC', clienttype: 'PILOT', frequency: '', latitude: '40.78223', longitude: '-103.41656', altitude: '26371', groundspeed: '508', planned_aircraft: 'B739/L', planned_tascruise: '452', planned_depairport: 'KDEN', planned_altitude: '35000', planned_destairport: 'KMSP', server: 'USA-WEST', protrevision: '100', rating: '1', transponder: '2200', facilitytype: '', visualrange: '', planned_revision: '0', planned_flighttype: 'I', planned_deptime: '2300', planned_actdeptime: '0', planned_hrsenroute: '2', planned_minenroute: '16', planned_hrsfuel: '4', planned_minfuel: '17', planned_altairport: 'KDSM', planned_remarks: 'Powered by simaware.ca /v/', planned_route: 'YOKES6 CHICI HAAND ONL FSD SSWAN TORGY3', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110211352', heading: '59', QNH_iHg: '29.918', QNH_Mb: '1013', 
    },
      { id: 21, name: 'KOFF (Offutt Air Force Base)', callsign: 'DAL2484', cid: '1182765', realname: 'Michael Levin KMSP', clienttype: 'PILOT', frequency: '', latitude: '33.76167', longitude: '-84.72504', altitude: '7993', groundspeed: '287', planned_aircraft: 'A320/L', planned_tascruise: '389', planned_depairport: 'KBHM', planned_altitude: '21000', planned_destairport: 'KATL', server: 'USA-EAST', protrevision: '100', rating: '1', transponder: '311', facilitytype: '', visualrange: '', planned_revision: '3', planned_flighttype: 'I', planned_deptime: '2135', planned_actdeptime: '2135', planned_hrsenroute: '0', planned_minenroute: '38', planned_hrsfuel: '2', planned_minfuel: '31', planned_altairport: 'KBNA', planned_remarks: '+VFPS+/V/RMK/POWERED BY SIMBRIEF', planned_route: 'BHM7 GUMMP DRSDN GNDLF2', planned_depairport_lat: '0', planned_depairport_lon: '0', planned_destairport_lat: '0', planned_destairport_lon: '0', atis_message: '', time_last_atis_received: '', time_logon: '20191110210333', heading: '90', QNH_iHg: '30.135', QNH_Mb: '1020', 
    },
  ];
/* backup funcitoning data below
export const HEROES: Hero[] = [
  { id: 11, name: 'KMSP (Minneapolis−Saint Paul International Airport)' },
  { id: 12, name: 'KDSM (Des Moines International Airport)' },
  { id: 13, name: 'KGRB (Green Bay Austin Straubel International Airport)' },
  { id: 14, name: 'KLNK (Lincoln Airport)' },
  { id: 15, name: 'KOFF (Offutt Air Force Base)' },
  { id: 16, name: 'KOMA (Eppley Airfield)' },
];

*/

